from app import app
from models import (
    db,
    PlottingFramework,
    SeriesType,
    Genre,
    PlottingPoint
)

def seed_data():
    with app.app_context():
        db.create_all()

        #---------------------------------------------------------
        # Insert Plotting Framework data
        f1 = PlottingFramework(name="7-Point Story Structure", description="Created by Dan Wells, the 7-Point story structure is all about pushing the protagonist from one event to the next. It is great for fast-paced, plot-driven stories", num_plot_points=7, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/7-Point-Plot-Structure-1.webp")
        f2 = PlottingFramework(name="27-Chapter Method", description="The 27-chapter method from Kat O’Keefe is sometimes referred to as the 3-Act 9-Block Method. It can create a story structure that is extremely well-defined, with clear arcs from beginning to end, from the outset. It's a great option for those who like to plan out exactly what is going to happen, when it will happen, and why it will happen.", num_plot_points=27, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/27-Chapter-Method-1.webp")
        f3 = PlottingFramework(name="Freytag’s Pyramid",description="Created by Gustav Freytag in the 1800's, Freytag’s Pyramid uses five acts to create a tragic plot structure that hinges on a central conflict ending in disaster.",num_plot_points=5, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/Freytag-s-Pyramid-2.webp")
        f4 = PlottingFramework(name="The Hero’s Journey",description="Created by Joseph Campbell and further developed by Christopher Vogler, The Hero's Journey is one of the most popular plot structures, especially in the fantasy genre. This type of plot focuses on a single character and the changes they go through in the story.",num_plot_points=12,img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/The-Hero-s-Journey-2.webp")
        f5 = PlottingFramework(name="Romancing the Beat",description="When Gwen Hayes created Romancing the Beat, she outlined a new structure specifically for plotting romance novels. By using this romance novel beat sheet, you can easily map your romance story from the meet-cute to the happily ever after (HEA) and all the messy in-between.",num_plot_points=20, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/Romancing-the-Beat-1.webp")
        f6 = PlottingFramework(name="Save the Cat Story Beats",description="Originally set forth by Blake Snyder in his book of the same name as a scriptwriting method, it has become a popular tool for novelists thanks to Jessica Brody's Save the Cat! Writes a Novel. It is a story structure that focuses on setting the pacing of a story.", num_plot_points=15, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/Save-the-Cat-Story-Structure-1.webp")
        f7 = PlottingFramework(name="Story Circle",description="Developed by the creator of popular television series such as Rick and Morty and Community, Dan Harmon’s Story Circle is a simplification of the Hero’s Journey. The method puts a strong emphasis on character development, focusing the plot more on internal motivations versus external factors.",num_plot_points=8, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/Story-Circle-1.webp")
        f8 = PlottingFramework(name="Three-Act Structure",description="This is the backbone of many other plotting methods. One could say that every story includes a three-act plot structure since every story has a beginning, a middle, and an ending. Ensuring that every chapter or scene follows a three-act structure template is a great way to ensure they each have an impactful function and identity.",num_plot_points=9, img_rep="https://jasonlouro.ghost.io/content/images/size/w1000/2023/08/Three-Act-Structure-1.webp")

        db.session.add(f1)
        db.session.add(f2)
        db.session.add(f3)
        db.session.add(f4)
        db.session.add(f5)
        db.session.add(f6)
        db.session.add(f7)
        db.session.add(f8)
        db.session.commit()

        print("Plotting Frameworks seeded!")

        # Data/Info obtained from:
        # https://www.campfirewriting.com/learn/narrative-structure

        #---------------------------------------------------------
        # Insert Series Type data
        s1 = SeriesType(name="Monology", num_of_books=1)
        s2 = SeriesType(name="Duology", num_of_books=2)
        s3 = SeriesType(name="Trilogy", num_of_books=3)
        s4 = SeriesType(name="Quartet", num_of_books=4)
        s5 = SeriesType(name="Pentology", num_of_books=5)
        s6 = SeriesType(name="Hexology", num_of_books=6)
        s7 = SeriesType(name="Heptalogy", num_of_books=7)

        db.session.add(s1)
        db.session.add(s2)
        db.session.add(s3)
        db.session.add(s4)
        db.session.add(s5)
        db.session.add(s6)
        db.session.add(s7)
        db.session.commit()

        print("Series Types seeded!")

        #---------------------------------------------------------
        # Insert Genre data
        g1 = Genre(name="Fantasy", description="Fantasy combines the imaginative fiction dependent for effect on strangeness of setting (such as other worlds or times) and of characters (such as supernatural or unnatural beings).  Science fiction can be seen as a form of fantasy, but the terms are not interchangeable, as science fiction usually is set in the future and is based on some aspect of science or technology, while fantasy is set in an imaginary world and features the magic of mythical beings.", avg_word_count=109000, min_word_count=27000, max_word_count=318000)
        g2 = Genre(name="Historical Fiction", description="Historical fiction has as its setting a period of history and that attempts to convey the spirit, manners, and social conditions of a past age with realistic detail and fidelity (which is in some cases only apparent fidelity) to historical fact.", avg_word_count=102000, min_word_count=6000, max_word_count=223000)
        g3 = Genre(name="Horror", description="Horror conveys a story in which the focus is on creating a feeling of fear. Such tales are of ancient origin and form a substantial part of the body of folk literature. They can feature supernatural elements such as ghosts, witches, or vampires, or they can address more realistic psychological fears.", avg_word_count=102000, min_word_count=19000, max_word_count=377000)
        g4 = Genre(name="Genre Fiction", description="Genre fiction follows specific genre conventions, using tropes, structures, plot points, and archetypes to tell a story.", avg_word_count=99000, min_word_count=6000, max_word_count=221000)
        g5 = Genre(name="Literary Fiction", description="In general, literary fiction cannot be categorized by any specific genre conventions, and which seeks to describe real-life reactions to complex events using well-developed characters, themes, literary devices, and experimentations in prose.", avg_word_count=98000, min_word_count=58000, max_word_count=163000)
        g6 = Genre(name="Science Fiction", description="Science fiction is a form of fiction that deals principally with the impact of actual or imagined science upon society or individuals.", avg_word_count=98000, min_word_count=11000, max_word_count=377000)
        g7 = Genre(name="Action/Adventure", description="The action/adventure genre features characters involved in exciting and usually dangerous activities and adventures.", avg_word_count=96000, min_word_count=16000, max_word_count=299000)
        g8 = Genre(name="Contemporary Fiction", description="Books in the contemporary fiction genre are made up of stories that could happen to real people in real settings. They usually take place in the same time period the reader is living (the present), with thigs that are currently, or could be happening, in the same time period.", avg_word_count=96000, min_word_count=33000, max_word_count=196000)
        g9 = Genre(name="Woman's Fiction", description="Woman's fiction features books that focus on women's life experience that are marketed to female readers, and includes many mainstream novels or women's rights books.", avg_word_count=94000, min_word_count=6000, max_word_count=163000)
        g10 = Genre(name="Mystery/Thriller/Suspense", description="A traditional mystery novel follows a detective of some sort, either amateur or professional, while they attempt to solve a crime. The reader usually follows the detective, discovering clues along with the characters. The detectives themselves are not usually in any real danger from the antagonist, and are often completely disconnected from the crime. Thrillers take the basic tenets of a mystery novel and add an element of danger to the protagonist, who may or may not be a detective in the traditional sense. Suspense novels are somewhat more rare as a standalone sub-genre, but still popular. While mysteries and thrillers are usually told from either the point of view or the perspective of the protagonist, narration in suspense stories is less defined. This is because suspense involves the reader knowing more than the protagonist, which we can only do if the narration is either omniscient or multi-perspective — that is, told from the point of view of more than one character. Suspense novels also employ time skipping in the narration; they often start either in media res or at the end, but with crucial details left out.", avg_word_count=91000, min_word_count=14000, max_word_count=196000)
        g11 = Genre(name="Romance", description="A romance novel or romantic novel is a genre fiction novel that primary focuses on the relationship and romantic love between two people, typically with an emotionally satisfying and optimistic ending.", avg_word_count=91000, min_word_count=19000, max_word_count=194000)
        g12 = Genre(name="Crime Fiction", description="Crime fiction is the genre of fiction that deals with crimes, their detection, criminals, and their motives.", avg_word_count=89000, min_word_count=24000, max_word_count=180000)
        g13 = Genre(name="Religious Fiction", description="Books in the religious fiction genre require element of religion (Christianity). They often deal with prophecy, angels, demons, spiritual choices, and inspirational encouragement of forgiveness and freedom from what hinders humanity.", avg_word_count=75000, min_word_count=13000, max_word_count=161000)
        g14 = Genre(name="Erotica", description="Erotica comprises fictional and factual stories and accounts of eros (passionate, romantic or sexual relationships) intended to arouse similar feelings in readers.", avg_word_count=58000, min_word_count=5000, max_word_count=157000)

        db.session.add(g1)
        db.session.add(g2)
        db.session.add(g3)
        db.session.add(g4)
        db.session.add(g5)
        db.session.add(g6)
        db.session.add(g7)
        db.session.add(g8)
        db.session.add(g9)
        db.session.add(g10)
        db.session.add(g11)
        db.session.add(g12)
        db.session.add(g13)
        db.session.add(g14)
        db.session.commit()

        print("Genres seeded!")

        # Data/Info obtained from:
        # https://kindlepreneur.com/how-many-words-in-a-novel/
        # https://www.britannica.com/art/fantasy-narrative-genre
        # https://www.britannica.com/art/historical-novel
        # https://www.britannica.com/art/horror-story
        # https://writers.com/literary-fiction-vs-genre-fiction
        # https://www.britannica.com/art/science-fiction/Mass-markets-and-juvenile-science-fiction
        # https://www.merriam-webster.com/dictionary/action-adventure
        # https://book-genres.com/contemporary-fiction-definition/
        # https://en.wikipedia.org/wiki/Women%27s_fiction
        # https://en.wikipedia.org/wiki/Romance_novel
        # https://bookriot.com/difference-between-mystery-suspense-and-thriller-novels/
        # https://www.findmeanauthor.com/crime_fiction.htm
        # https://book-genres.com/religious-fiction-genre/
        # https://en.wikipedia.org/wiki/Erotic_literature
        # 

        #---------------------------------------------------------
        # Insert Plotting Point data
        pp1 = PlottingPoint(plot_step=1, percent_of_story=1/7, title="Hook: Establish the status quo.", description="The hook serves as an introduction to the story, establishing the status quo and introducing the audience to the characters and the world. We should meet the protagonist here and learn more about them and how they interact with the setting.", framework_id=1)
        pp2 = PlottingPoint(plot_step=2, percent_of_story=1/7, title="Plot Turn 1: The inciting incident.", description="The first plot turn breaks away from the status quo in what is more commonly known as an inciting incident. This is usually an outside force calling the protagonist to action, pushing them away from their status quo.", framework_id=1)
        pp3 = PlottingPoint(plot_step=3, percent_of_story=1/7, title="Pinch 1: The situation escalates.", description="The first pinch raises the stakes. This can include introducing villains, placing your characters in more dangerous situations, or putting obstacles in their way. No matter what direction the plot takes here, it should establish major challenges or dangers for the characters.", framework_id=1)
        pp4 = PlottingPoint(plot_step=4, percent_of_story=1/7, title="Midpoint: The protagonist changes from being reactive to proactive.", description="At the midpoint, the protagonist makes a conscious decision to take charge of the situation. Up to this point in the story, they’ve been reacting to the outside world. From here on, the protagonist will be the driving force of the plot.", framework_id=1)
        pp5 = PlottingPoint(plot_step=5, percent_of_story=1/7, title="Pinch 2: A major setback occurs.", description="Things go from bad to worse in the second pinch. No matter what the protagonist has endured or achieved so far, things should seem at their most hopeless here. Depending on the type of story, this can be a death, the team splitting up, or the villain obtaining the McGuffin that will end the world.", framework_id=1)
        pp6 = PlottingPoint(plot_step=6, percent_of_story=1/7, title="Plot Turn 2: The key to victory is discovered.", description="The second plot turn is the final skin-of-their-teeth moment where the protagonist finds what they need to overcome the big bad. This could be anything, but it is usually an object or a lesson. It could be the magical sword, the magic within, or the realization that the true magic was the friends they made along the way.", framework_id=1)
        pp7 = PlottingPoint(plot_step=7, percent_of_story=1/7, title="Resolution: The conflict is resolved.", description="The resolution wraps it all up. The conflict gets resolved, the big bad might get their due, and the hero settles into a new status quo. In classical plotting parlance, this includes both the climax and the denouement, and I usually spread these between two chapters.", framework_id=1)
        pp8 = PlottingPoint(plot_step=1, percent_of_story=1/27, title="Act 1: Intro", description="The reader meets the main character and sees them in their normal life.", framework_id=2)
        pp9 = PlottingPoint(plot_step=2, percent_of_story=1/27, title="Act 1: Inciting Incident", description="Something happens to disrupt the main character’s ordinary life.", framework_id=2)
        pp10 = PlottingPoint(plot_step=3, percent_of_story=1/27, title="Act 1: Fallout", description="The main character immediately reacts to the inciting incident.", framework_id=2)
        pp11 = PlottingPoint(plot_step=4, percent_of_story=1/27, title="Act 1: Reaction/Rebellion", description="The main character pushes back against what happened or was revealed in the inciting incident.", framework_id=2)
        pp12 = PlottingPoint(plot_step=5, percent_of_story=1/27, title="Act 1: Action", description="The hero takes action to fix what happened in the inciting incident.", framework_id=2)
        pp13 = PlottingPoint(plot_step=6, percent_of_story=1/27, title="Act 1: Consequence", description="The main character must face the consequences of the action they took (or tried to take).", framework_id=2)
        pp14 = PlottingPoint(plot_step=7, percent_of_story=1/27, title="Act 1: Pressure", description="The main character starts to feel the weight of what’s happening to them.", framework_id=2)
        pp15 = PlottingPoint(plot_step=8, percent_of_story=1/27, title="Act 1: Pinch", description="A plot twist happens, making the main character wonder if they made the right decision when they decided to take action.", framework_id=2)
        pp16 = PlottingPoint(plot_step=9, percent_of_story=1/27, title="Act 1: Push", description="The main character is forced once and for all out of their ordinary world.", framework_id=2)
        pp17 = PlottingPoint(plot_step=10, percent_of_story=1/27, title="Act 2: New World", description="The main character explores the shiny new world (or state of mind) they’re now living in.", framework_id=2)
        pp18 = PlottingPoint(plot_step=11, percent_of_story=1/27, title="Act 2: Fun & Games", description="The protagonist plays around in the new world, potentially meeting new characters.", framework_id=2)
        pp19 = PlottingPoint(plot_step=12, percent_of_story=1/27, title="Act 2: Juxtaposition", description="We see a contrast between the main character’s new world to the ordinary world they left behind.", framework_id=2)
        pp20 = PlottingPoint(plot_step=13, percent_of_story=1/27, title="Act 2: Buildup", description="Complications occur: the main character faces some serious struggles, internal or external.", framework_id=2)
        pp21 = PlottingPoint(plot_step=14, percent_of_story=1/27, title="Act 2: Midpoint", description="Something big happens that changes everything for your main character.", framework_id=2)
        pp22 = PlottingPoint(plot_step=15, percent_of_story=1/27, title="Act 2: Reversal", description="The main character decides on a new course of action based on what’s been revealed at the midpoint.", framework_id=2)
        pp23 = PlottingPoint(plot_step=16, percent_of_story=1/27, title="Act 2: Consequence", description="The hero reflects on all that’s happened to them on their journey so far.", framework_id=2)
        pp24 = PlottingPoint(plot_step=17, percent_of_story=1/27, title="Act 2: Trials", description="The protagonist takes action to solve their problems and makes progress based on the lessons they’ve learned in previous conflicts.", framework_id=2)
        pp25 = PlottingPoint(plot_step=18, percent_of_story=1/27, title="Act 2: Dedication", description="Despite the challenges they’re facing, the main character resolves to solve their issues.", framework_id=2)
        pp26 = PlottingPoint(plot_step=19, percent_of_story=1/27, title="Act 3: Calm Before the Storm", description="The hero feels the pressure as they decide to put their plan into action.", framework_id=2)
        pp27 = PlottingPoint(plot_step=20, percent_of_story=1/27, title="Act 3: Plot Twist", description="Something terrible occurs, the worst complication in the story to this point.", framework_id=2)
        pp28 = PlottingPoint(plot_step=21, percent_of_story=1/27, title="Act 3: Darkest Point", description="The main character is at their lowest. Is all lost?", framework_id=2)
        pp29 = PlottingPoint(plot_step=22, percent_of_story=1/27, title="Act 3: Power Within", description="The hero reaches deep inside to bring themselves back from the brink of destruction.", framework_id=2)
        pp30 = PlottingPoint(plot_step=23, percent_of_story=1/27, title="Act 3: Action", description="With renewed resolve, the protagonist formulates a plan to take action.", framework_id=2)
        pp31 = PlottingPoint(plot_step=24, percent_of_story=1/27, title="Act 3: Convergence", description="All of the characters and main plot points gather for the big finale.", framework_id=2)
        pp32 = PlottingPoint(plot_step=25, percent_of_story=1/27, title="Act 3: The Final Battle", description="The hero faces down their nemesis. This scene is not always a literal battle: sometimes, the hero is tackling an internal demon in a high-pressure situation (like declaring their eternal love before a big group of people).", framework_id=2)
        pp33 = PlottingPoint(plot_step=26, percent_of_story=1/27, title="Act 3: Climax", description="Everything has led to this moment. The hero succeeds or fails, depending on your story.", framework_id=2)
        pp34 = PlottingPoint(plot_step=27, percent_of_story=1/27, title="Act 3: Resolution", description="We see the hero in the aftermath of the climax. Are they celebrating their victory or licking their wounds?", framework_id=2)
        pp35 = PlottingPoint(plot_step=1, percent_of_story=1/5, title="Introduction", description="Establishes the status quo.", framework_id=3)
        pp36 = PlottingPoint(plot_step=2, percent_of_story=1/5, title="Rising Action", description="Events push the characters out of their comfort zone, gradually increasing in scope and scale.", framework_id=3)
        pp37 = PlottingPoint(plot_step=3, percent_of_story=1/5, title="Climax", description="The situation drastically changes for the worse.", framework_id=3)
        pp38 = PlottingPoint(plot_step=4, percent_of_story=1/5, title="Falling Action", description="The consequences of the climax impact the protagonist", framework_id=3)
        pp39 = PlottingPoint(plot_step=5, percent_of_story=1/5, title="Catastrophe", description="An ultimate failure or loss.", framework_id=3)
        pp40 = PlottingPoint(plot_step=1, percent_of_story=1/12, title="Act 1: Ordinary World", description="The journey begins with the status quo—business as usual. We meet the hero and are introduced to the Known World they live in. In other words, this is your exposition, the starting stuff that establishes the story to come.", framework_id=4)
        pp41 = PlottingPoint(plot_step=2, percent_of_story=1/12, title="Act 1: Call to Adventure", description="The inciting incident takes place and the hero is called to act upon it. While they're still firmly in the Known World, the story kicks off and leaves the hero feeling out of balance. In other words, they are placed at a crossroads.", framework_id=4)
        pp42 = PlottingPoint(plot_step=3, percent_of_story=1/12, title="Act 1: Refusal of the Call", description="The hero hesitates and instead refuses their call to action. Following the call would mean making a conscious decision to break away from the status quo. Ahead lies danger, risk, and the unknown; but here and now, the hero is still in the safety and comfort of what they know.", framework_id=4)
        pp43 = PlottingPoint(plot_step=4, percent_of_story=1/12, title="Act 1: Meet the Mentor", description="The protagonist receives knowledge or motivation from a powerful or influential figure. This is a tactical move on the hero's part—remember that it was only the previous step in which they debated whether or not to jump headfirst into the unknown. By Meeting the Mentor, they can gain new information or insight, and better equip themselves for the journey they might to embark on.", framework_id=4)
        pp44 = PlottingPoint(plot_step=5, percent_of_story=1/12, title="Act 2: Crossing the Threshold", description="The hero leaves the Known World to face the Unknown World. They are fully committed to the journey, with no way to turn back now. There may be a confrontation of some sort, and the stakes will be raised.", framework_id=4)
        pp45 = PlottingPoint(plot_step=6, percent_of_story=1/12, title="Act 2: Tests, Allies, Enemies", description="The hero explores the Unknown World. Now that they have firmly crossed the threshold from the Known World, the hero will face new challenges and possibly meet new enemies. They'll have to call upon their allies, new and old, in order to keep moving forward.", framework_id=4)
        pp46 = PlottingPoint(plot_step=7, percent_of_story=1/12, title="Act 2: Innermost Cave", description="The hero nears the goal of their quest, the reason they crossed the threshold in the first place. Here, they could be making plans, having new revelations, or gaining new skills. To put it in other familiar terms, this step would mark the moment just before the story's climax.", framework_id=4)
        pp47 = PlottingPoint(plot_step=8, percent_of_story=1/12, title="Act 2: Ordeal", description="The hero faces a dire situation that changes how they view the world. All threads of the story come together at this pinnacle, the central crisis from which the hero will emerge unscathed or otherwise. The stakes will be at their absolute highest here. Vogler details that in this stage, the hero will experience a 'death,'' though it need not be literal. In your story, this could signify the end of something and the beginning of another, which could itself be figurative or literal. For example, a certain relationship could come to an end, or it could mean someone 'stuck in their ways' opens up to a new perspective.", framework_id=4)
        pp48 = PlottingPoint(plot_step=9, percent_of_story=1/12, title="Act 2: Reward", description="This is it, the moment the hero has been waiting for. They've survived 'death,'' weathered the crisis of The Ordeal, and earned the Reward for which they went on this journey.", framework_id=4)
        pp49 = PlottingPoint(plot_step=10, percent_of_story=1/12, title="Act 3: The Road Back", description="It's time for the journey to head towards its conclusion. The hero begins their return to the Known World and may face unexpected challenges. Whatever happens, the 'why' remains paramount here (i.e. why the hero ultimately chose to embark on their journey). This step marks a final turning point where they'll have to take action or make a decision to keep moving forward and be 'reborn' back into the Known World.", framework_id=4)
        pp50 = PlottingPoint(plot_step=11, percent_of_story=1/12, title="Act 3: Resurrection", description="The hero faces their ultimate challenge and emerges victorious, but forever changed. This step often requires a sacrifice of some sort, and having stepped into the role of The Hero, they must answer to this.", framework_id=4)
        pp51 = PlottingPoint(plot_step=12, percent_of_story=1/12, title="Act 3: Return With Elixir", description="Finally, the hero returns home as a new version of themself, the elixir is shared amongst the people, and the journey is completed full circle. The elixir, like many other elements of the hero's journey, can be literal or figurative. It can be a tangible thing, such as an actual elixir meant for some specific purpose, or it could be represented by an abstract concept such as hope, wisdom, or love.", framework_id=4)
        pp52 = PlottingPoint(plot_step=1, percent_of_story=1/20, title="Phase 1: Intro Character 1", description="During The Setup, you must introduce your first main character and show why they are compelling. Give your readers a look at the characters’ normal lives before they’re turned upside down by true love.", framework_id=5)
        pp53 = PlottingPoint(plot_step=2, percent_of_story=1/20, title="Phase 1: Intro Character 2", description="During The Setup, you must introduce your second main character and show why they are compelling. Give your readers a look at the characters’ normal lives before they’re turned upside down by true love.", framework_id=5)
        pp54 = PlottingPoint(plot_step=3, percent_of_story=1/20, title="Phase 1: Meet Cute", description="This beat is when your two main characters meet for the first time. This moment should be memorable, though it doesn’t actually have to be cute. ", framework_id=5)
        pp55 = PlottingPoint(plot_step=4, percent_of_story=1/20, title="Phase 1: No Way 1", description="During this beat, one of your main characters should explain (internally or externally) why they most assuredly will not be falling in love with the love interest they just collided with.", framework_id=5)
        pp56 = PlottingPoint(plot_step=5, percent_of_story=1/20, title="Phase 1: Adhesion Plot Thrust", description="Your main characters have met and sworn that they are not falling in love. Fortunately for them (and fans of true love), the Adhesion beat is next. In this beat, something happens to keep your main characters close to each other for the duration of the story.", framework_id=5)
        pp57 = PlottingPoint(plot_step=6, percent_of_story=1/20, title="Phase 2: No Way 2", description="Despite the fact that your main characters are stuck together, they will want to fight their feelings. The No Way #2 beat offers an opportunity to reiterate why this relationship simply won’t work.", framework_id=5)
        pp58 = PlottingPoint(plot_step=7, percent_of_story=1/20, title="Phase 2: Inkling", description="This beat is where your characters start to realize that they might fall in love. Perhaps they get a look at a different side of each other, or have an inexplicably romantic moment.", framework_id=5)
        pp59 = PlottingPoint(plot_step=8, percent_of_story=1/20, title="Phase 2: Deepening Desire", description="There’s no denying it anymore: your characters are falling for each other. This beat shows the characters growing closer.", framework_id=5)
        pp60 = PlottingPoint(plot_step=9, percent_of_story=1/20, title="Phase 2: Maybe This could Work", description="Your characters start to believe that love could work—there’s something different about their connection than what they’ve experienced before.", framework_id=5)
        pp61 = PlottingPoint(plot_step=10, percent_of_story=1/20, title="Phase 2: Midpoint of Love Plot Thrust", description="Where there’s smoke, there’s fire. The sparks have been flying between your two main characters and at the midpoint, the tension culminates in an expression of their affection, usually through a kiss (or maybe something more).", framework_id=5)
        pp62 = PlottingPoint(plot_step=11, percent_of_story=1/20, title="Phase 3: Inkling Doubt", description="After the high of their connection at the midpoint, uncertainty sets in. The love interests start to let their fears get the better of them once again.", framework_id=5)
        pp63 = PlottingPoint(plot_step=12, percent_of_story=1/20, title="Phase 3: Deepening Doubt", description="Insecurities are running high. Maybe your main characters have a misunderstanding or are driven apart. Whatever reasons they had for not falling in love back from the No Way beats are exploited in this section.",framework_id=5)
        pp64 = PlottingPoint(plot_step=13, percent_of_story=1/20, title="Phase 3: Retreat", description="It’s all becoming too much. To stay safe, your love interests retreat and continue to misunderstand each other. There is too much pain in their connection. Maybe they won’t be able to overcome their internal flaws and be together. ", framework_id=5)
        pp65 = PlottingPoint(plot_step=14, percent_of_story=1/20, title="Phase 3: Shields Up", description="It happened again. Your characters trusted someone else, but they were let down. During this beat, they reaffirm their commitment to hardening their hearts and being alone.", framework_id=5)
        pp66 = PlottingPoint(plot_step=15, percent_of_story=1/20, title="Phase 3: Breakup", description="It’s over. The breakup might have happened during the shields-up moment, but it’s permanent now. (Or is it?)", framework_id=5)
        pp67 = PlottingPoint(plot_step=16, percent_of_story=1/20, title="Phase 4: Dark Night", description="Your characters wallow after their break up. How did things go so wrong again?", framework_id=5)
        pp68 = PlottingPoint(plot_step=17, percent_of_story=1/20, title="Phase 4: Wake Up", description="After some time in the darkness, the sun rises again. Your characters realize that they have agency—they are choosing to be miserable, and they can choose to be happy. They just need to address their flaws, once and for all.", framework_id=5)
        pp69 = PlottingPoint(plot_step=18, percent_of_story=1/20, title="Phase 4: Grand Gesture", description="Cue the boom box. It’s time for a big moment. One of your characters takes a big risk to show the other that they have changed and that their love can conquer all.", framework_id=5)
        pp70 = PlottingPoint(plot_step=19, percent_of_story=1/20, title="Phase 4: Whole Hearted", description="It worked! Your characters are together, They have addressed the individual issues that kept them apart and are ready for their happily ever after.", framework_id=5)
        pp71 = PlottingPoint(plot_step=20, percent_of_story=1/20, title="Phase 4: Epilogue", description="Romance readers love a sneak peek into the future: what does it look like for your characters to be living their lives completely and together?", framework_id=5)
        pp72 = PlottingPoint(plot_step=1, percent_of_story=0.01, title="Act 1: Opening Image", description="The Opening Image is a 'before' snapshot of your hero: who they are and what their world is like. Your reader should immediately get a sense of what your hero is like as a person, as well as what their ordinary world is like before the events of the Catalyst change everything.", framework_id=6)
        pp73 = PlottingPoint(plot_step=2, percent_of_story=0.01, title="Act 1: Theme Stated", description="In the Theme Stated beat, a character (typically not the hero) hints at the life lesson the hero must learn or discover to complete their arc. Remember, Save the Cat isn’t just about creating a tight plot: it’s also about crafting an emotionally satisfying story where the main character undergoes a profound transformation. During this beat, you foreshadow what that change might be.", framework_id=6)
        pp74 = PlottingPoint(plot_step=3, percent_of_story=0.08, title="Act 1: Setup", description="The Setup explores the hero’s present circumstances, establishing their primary goal or goals, and introducing support characters. This section is important because it helps flesh out the main character and their world.", framework_id=6)
        pp75 = PlottingPoint(plot_step=4, percent_of_story=0.01, title="Act 1: Catalyst", description="Often known in other plotting methods as the inciting incident, the Catalyst is what catapults the hero into their new world (or way of thinking). This event forever changes the hero—they cannot go back to their old way of living.", framework_id=6)
        pp76 = PlottingPoint(plot_step=5, percent_of_story=0.09, title="Act 1: Debate", description="In the Debate beat, the hero expresses reluctance to take the action required by the Catalyst. This beat is all about asking questions. The hero might wonder things like, 'Should I do this?' or 'Can I do this?' or 'Is this right for me?'", framework_id=6)
        pp77 = PlottingPoint(plot_step=6, percent_of_story=0.01, title="Act 2: Break Into Two", description="The hero takes action. They leave their old world or way of thinking behind and forever enter a new state.", framework_id=6)
        pp78 = PlottingPoint(plot_step=7, percent_of_story=0.02, title="Act 2: B Story", description="The B Story introduces a subplot, typically in the form of a new character that will help the hero learn their ultimate lesson. The B Story character is often a love interest, mentor, friend, or nemesis.", framework_id=6)
        pp79 = PlottingPoint(plot_step=8, percent_of_story=0.27, title="Act 2: Fun and Games", description="The Fun and Games beat is the longest beat in the entire novel. We follow the hero through a series of ups and downs, challenges and successes, as they explore their new world or way of thinking. This beat isn’t necessarily about having fun, though some protagonists might. What specifically happens will depend on your story type and the transformation your hero needs to undergo. Typically, during the Fun and Games section, heroes are either on an upward path (experiencing a general trend toward success) or a downward path (experiencing a general trend toward struggle and failure).", framework_id=6)
        pp80 = PlottingPoint(plot_step=9, percent_of_story=0.01, title="Act 2: Midpoint", description="The Fun and Games section of your story leads to a pivotal moment: the Midpoint. At this beat, the hero experiences a False Victory or False Defeat that raises the stakes and pushes them toward their key transformation. If your hero experiences a False Victory, they might be lulled into thinking that their problems are fixed and they won’t experience any more struggles. If they experience a False Defeat, they might worry that they are doomed to failure. Either way, the hero is wrong: there’s still a lot of story left!", framework_id=6)
        pp81 = PlottingPoint(plot_step=10, percent_of_story=0.24, title="Act 2: Bad Guys Close In", description="After the Midpoint, events start escalating for the hero. Their flaws are starting to catch up to them and they learn quickly that the False Victory or Defeat they experienced was indeed false. Your hero hasn’t truly changed yet and so they will continue to struggle until they learn their lesson and complete their transformation.", framework_id=6)
        pp82 = PlottingPoint(plot_step=11, percent_of_story=0.01, title="Act 2: All is Lost", description="All is Lost is the lowest point of the novel, where the hero hits rock bottom. Their flaws have caught up to them and something has happened to push them to their breaking point. It’s important that the All is Lost moment is in some way caused by the hero: whether by their choices or actions, this terrible experience will force the hero to reflect and make a change moving forward.", framework_id=6)
        pp83 = PlottingPoint(plot_step=12, percent_of_story=0.04, title="Act 2: Dark Night of the Soul", description="Defeated, the hero processes everything that’s happened to them thus far. In this beat, the hero wallows in the aftermath of the All is Lost beat, wondering how their life has ended up this badly and what they can possibly do to turn things around. The hero typically has an epiphany that their circumstances are a result of their own actions or beliefs.", framework_id=6)
        pp84 = PlottingPoint(plot_step=13, percent_of_story=0.01, title="Act 3: Break Into Three", description="Good news for your hero. All isn’t lost! In this beat, the hero has an a-ha moment and realizes what they must do to fix their problems. They begin to put a plan in place to fix what’s been broken.", framework_id=6)
        pp85 = PlottingPoint(plot_step=14, percent_of_story=0.19, title="Act 3: The Finale", description="During the Finale, the hero successfully develops and enacts a plan to fix their problems, thereby resolving the main conflict of the story. This beat gives your hero a chance to prove that they have learned the lessons of Act III and can change for the better.", framework_id=6)
        pp86 = PlottingPoint(plot_step=15, percent_of_story=0.01, title="Act 3: Final Image", description="We get a final snapshot of the hero, forever changed by their journey, to contrast where they were in the Opening Image. This beat should parallel the Opening Image and show both the hero and the readers how far your main character has come.", framework_id=6)
        pp87 = PlottingPoint(plot_step=1, percent_of_story=1/8, title="Step 1: Zone of Comfort", description="We don’t have to like your protagonist—we just need to connect with them in some way. This step is also sometimes referred to as a place of comfort. It’s when we are introduced to most of our main characters and see what “normal” looks like for them.", framework_id=7)
        pp88 = PlottingPoint(plot_step=2, percent_of_story=1/8, title="Step 2: Need or Desire", description="Your hero is incomplete. They need to rescue a loved one, or win a tournament, or escape capture. By now we should have a good idea about the kind of story you’re telling, and the main character’s primary motivations.", framework_id=7)
        pp89 = PlottingPoint(plot_step=3, percent_of_story=1/8, title="Step 3: Crossing a Threshold", description="Your protagonist has accepted the call to adventure and begins their quest, traveling—literally or figuratively—into an unfamiliar world. They’re actively going after whatever it is they need, or what they think they need.", framework_id=7)
        pp90 = PlottingPoint(plot_step=4, percent_of_story=1/8, title="Step 4: Road of Trials", description="This section can also be summed up as a period where your characters have to adapt to the new situation. There are obstacles between them and their goals which they need to overcome.", framework_id=7)
        pp91 = PlottingPoint(plot_step=5, percent_of_story=1/8, title="Step 5: Get What They Want", description="However, “getting what they want” isn’t always a positive experience. Your protagonist might find that what they wanted wasn’t actually that great, they’d been lied to, or that what they wanted doesn’t last.", framework_id=7)
        pp92 = PlottingPoint(plot_step=6, percent_of_story=1/8, title="Step 6: Pay a Heavy Price", description="It’s almost impossible to discuss success without the cost paid for it. The best examples of a heavy price push your protagonist to the brink. They may have gotten what they wanted, but they lost a loved one, are forced to question their morals, or a secret is exposed. There are consequences for everyone’s actions—especially the protagonist’s.", framework_id=7)
        pp93 = PlottingPoint(plot_step=7, percent_of_story=1/8, title="Step 7: Return to Comfort", description="Your protagonist returns to the familiar world.", framework_id=7)
        pp94 = PlottingPoint(plot_step=8, percent_of_story=1/8, title="Step 8: Having Changed", description="The experience has changed your protagonist. They’ve learned and grown from the experience. Sometimes this is when the final showdown occurs—one last battle between the protagonist and antagonist. Sometimes it’s just a reflection of your protagonist applying what they’ve learned earlier in the story.", framework_id=7)
        pp95 = PlottingPoint(plot_step=1, percent_of_story=1/9, title="Act 1: Exposition", description="This initial phase introduces the protagonist, setting, and key relationships.", framework_id=8)
        pp96 = PlottingPoint(plot_step=2, percent_of_story=1/9, title="Act 1: Inciting Incident", description="The inciting incident is a pivotal event that propels the protagonist into the main action of the story.", framework_id=8)
        pp97 = PlottingPoint(plot_step=3, percent_of_story=1/9, title="Act 1: Consequence", description="Marking the end of Act One, this turning point decisively commits the protagonist to their journey.", framework_id=8)
        pp98 = PlottingPoint(plot_step=4, percent_of_story=1/9, title="Act 2: Rising Action", description="The rising action ramps up the stakes and deepens the protagonist's challenges and conflicts.", framework_id=8)
        pp99 = PlottingPoint(plot_step=5, percent_of_story=1/9, title="Act 2: Midpoint", description="The midpoint injects a significant twist or revelation that changes the story's direction.", framework_id=8)
        pp100 = PlottingPoint(plot_step=6, percent_of_story=1/9, title="Act 2: Consequence", description="This turning point dramatically increases the tension and paves the way for the climax.", framework_id=8)
        pp101 = PlottingPoint(plot_step=7, percent_of_story=1/9, title="Act 3: Build-up", description="The pre-climax (also called the Buildup) is the moment right before the climax, where the tension and anticipation are at their highest.", framework_id=8)
        pp102 = PlottingPoint(plot_step=8, percent_of_story=1/9, title="Act 3: Climax", description="The climax is the story's most intense moment, the confrontation or event all the action has been building towards.", framework_id=8)
        pp103 = PlottingPoint(plot_step=9, percent_of_story=1/9, title="Act 3: Resolution", description="The denouement ties up the narrative's loose ends and resolves the story’s conflicts.", framework_id=8)

        db.session.add(pp1)
        db.session.add(pp2)
        db.session.add(pp3)
        db.session.add(pp4)
        db.session.add(pp5)
        db.session.add(pp6)
        db.session.add(pp7)
        db.session.add(pp8)
        db.session.add(pp9)
        db.session.add(pp10)
        db.session.add(pp11)
        db.session.add(pp12)
        db.session.add(pp13)
        db.session.add(pp14)
        db.session.add(pp15)
        db.session.add(pp16)
        db.session.add(pp17)
        db.session.add(pp18)
        db.session.add(pp19)
        db.session.add(pp20)
        db.session.add(pp21)
        db.session.add(pp22)
        db.session.add(pp23)
        db.session.add(pp24)
        db.session.add(pp25)
        db.session.add(pp26)
        db.session.add(pp27)
        db.session.add(pp28)
        db.session.add(pp29)
        db.session.add(pp30)
        db.session.add(pp31)
        db.session.add(pp32)
        db.session.add(pp33)
        db.session.add(pp34)
        db.session.add(pp35)
        db.session.add(pp36)
        db.session.add(pp37)
        db.session.add(pp38)
        db.session.add(pp39)
        db.session.add(pp40)
        db.session.add(pp41)
        db.session.add(pp42)
        db.session.add(pp43)
        db.session.add(pp44)
        db.session.add(pp45)
        db.session.add(pp46)
        db.session.add(pp47)
        db.session.add(pp48)
        db.session.add(pp49)
        db.session.add(pp50)
        db.session.add(pp51)
        db.session.add(pp52)
        db.session.add(pp53)
        db.session.add(pp54)
        db.session.add(pp55)
        db.session.add(pp56)
        db.session.add(pp57)
        db.session.add(pp58)
        db.session.add(pp59)
        db.session.add(pp60)
        db.session.add(pp61)
        db.session.add(pp62)
        db.session.add(pp63)
        db.session.add(pp64)
        db.session.add(pp65)
        db.session.add(pp66)
        db.session.add(pp67)
        db.session.add(pp68)
        db.session.add(pp69)
        db.session.add(pp70)
        db.session.add(pp71)
        db.session.add(pp72)
        db.session.add(pp73)
        db.session.add(pp74)
        db.session.add(pp75)
        db.session.add(pp76)
        db.session.add(pp77)
        db.session.add(pp78)
        db.session.add(pp79)
        db.session.add(pp80)
        db.session.add(pp81)
        db.session.add(pp82)
        db.session.add(pp83)
        db.session.add(pp84)
        db.session.add(pp85)
        db.session.add(pp86)
        db.session.add(pp87)
        db.session.add(pp88)
        db.session.add(pp89)
        db.session.add(pp90)
        db.session.add(pp91)
        db.session.add(pp92)
        db.session.add(pp93)
        db.session.add(pp94)
        db.session.add(pp95)
        db.session.add(pp96)
        db.session.add(pp97)
        db.session.add(pp98)
        db.session.add(pp99)
        db.session.add(pp100)
        db.session.add(pp101)
        db.session.add(pp102)
        db.session.add(pp103)

        db.session.commit()

        print("Plot Point data seeded!")

        # Data/Info obtained from:
        # https://www.campfirewriting.com/learn/narrative-structure
        # https://www.campfirewriting.com/learn/seven-point-story-structure
        # https://www.campfirewriting.com/learn/27-chapter-outline
        # https://www.campfirewriting.com/learn/heros-journey
        # https://www.campfirewriting.com/learn/romancing-the-beat
        # https://www.campfirewriting.com/learn/save-the-cat-story-structure
        # https://www.campfirewriting.com/learn/outline-a-novel-story-circle
        # https://www.campfirewriting.com/learn/three-act-structure


seed_data()